### ISSUE TITLE
Address fields when backing a project are not suitable for a Welsh address

### ISSUE THREAD

**Issue by maredudd** [meigwilym/cytarse#68] opened 2015-04-01 19:21 UTC
**Steps to reproduce**

1. Log out
2. Go to the URL of a live project
3. Click to back the project
4. Log in

**Expected behaviour**

A form should be available to enter your address.  This form should be suitable for a Welsh address - although it can be quite generic since there would be worldwide backers.

**Actual behaviour**

The form is not suitable for a Welsh address, with 'number' coming after 'street' and there's a 'neighbourhood' field.  There also seems to be an error in the middle of the form where it says "#= form.input :address_complement, required: false, as: :string".  See the image below:

![image](https://cloud.githubusercontent.com/assets/3416991/6949488/0626b022-d8b5-11e4-815f-00737ee852e5.png)

**Comment by maredudd** [comment] 2015-04-01 19:23
The phone number format is also unsuitable:

![image](https://cloud.githubusercontent.com/assets/3416991/6949557/5c738c8e-d8b5-11e4-80b1-09046132b244.png)

**Comment by MattHall** [comment] 2015-04-15 19:48
Related to #9

**Comment by MattHall** [comment] 2015-04-15 19:54
Closing as duplicate of #9

**Closed by MattHall** 2015-04-15 19:54 UTC
